### ISSUE TITLE
Ajouter le lien du replay

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/bbb-session-insights#2]
On peut aussi ajouter facilement le lien du replay associé car tu as déjà l'id du cours et de la session, ie :

https://bbb2.oclock.school/playback/presentation/2.3/10f87b211ab57aa944a797c9ba5fdae3b49590fc-1711547005158

**Comment by HerosDuGouter** [comment]
J'ai ajouté une fonctionnalité qui regarde si un replay existe pour un cours donné et met un bouton vert cliquable si c'est le cas, ou grisé si ça n'est pas le cas.
