### ISSUE TITLE
BSI: Paginate results

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/bbb-session-insights#4]
🇬‍🇧 You'll need to paginate the results and display only the first 50, for example, plus a page selection system.

🇫‍🇷 Il faudra paginer les résultats et afficher par exemple uniquement les 50 premiers, plus un système de sélection de page.

**Comment by pmaldi** [comment]
This issue is done with current dev branch no ?

**Comment by clementgineste** [comment]
> This issue is done with current dev branch no ?

yep
